// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/24/2026, 6:16:37 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/hariman/Development/Leads_tracker/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hariman/Development/Leads_tracker/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hariman/Development/Leads_tracker/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hariman/Development/Leads_tracker/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hariman/Development/Leads_tracker/frontend/plugins/**/*.{js,ts,mjs}","/Users/hariman/Development/Leads_tracker/frontend/composables/**/*.{js,ts,mjs}","/Users/hariman/Development/Leads_tracker/frontend/utils/**/*.{js,ts,mjs}","/Users/hariman/Development/Leads_tracker/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hariman/Development/Leads_tracker/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/hariman/Development/Leads_tracker/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/hariman/Development/Leads_tracker/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;